name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      has_frontend: ${{ steps.chk.outputs.has_frontend }}
      has_backend: ${{ steps.chk.outputs.has_backend }}
    steps:
      - uses: actions/checkout@v4
      - id: chk
        shell: bash
        run: |
          if [ -f frontend/package.json ]; then
            echo "has_frontend=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_frontend=false" >> "$GITHUB_OUTPUT"
          fi

          if [ -f backend/package.json ]; then
            echo "has_backend=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_backend=false" >> "$GITHUB_OUTPUT"
          fi

  frontend:
    needs: detect
    if: needs.detect.outputs.has_frontend == 'true'
    name: Frontend (frontend/)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run lint --if-present
      - run: npm test --if-present -- --ci --passWithNoTests
      - run: npm run build --if-present

  backend:
    needs: detect
    if: needs.detect.outputs.has_backend == 'true'
    name: Backend (backend/)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            backend/yarn.lock
            backend/pnpm-lock.yaml
      - run: npm ci || npm install
      - run: npm run lint --if-present
      - run: npm test --if-present -- --ci --passWithNoTests
      - run: npm run build --if-present

